name: continuous-integration-tests
on:
  push

jobs:
  check-conventional-commits:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: ensure-conventional-commits
        uses: ohpensource/platform-cicd/actions/git/ensure-conventional-commits@8ab4546a8adab2138e3c5389f55cd969cd091e68
        with:
          base-branch: $GITHUB_BASE_REF
          pr-branch: $GITHUB_HEAD_REF

